// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks_service is a generated GoMock package.
package mocks_service

import (
	model "github.com/galihsatriawan/nested-call-mock/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Eligible mocks base method.
func (m *MockService) Eligible(id int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eligible", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Eligible indicates an expected call of Eligible.
func (mr *MockServiceMockRecorder) Eligible(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eligible", reflect.TypeOf((*MockService)(nil).Eligible), id)
}

// GetUserByID mocks base method.
func (m *MockService) GetUserByID(id int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockServiceMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockService)(nil).GetUserByID), id)
}
